const THEME_EMOJI: Record<string, string> = {
  butterflies: "🦋",
  bubbles: "🫧",
  stars: "⭐",
  fish: "🐟",
  balloons: "🎈",
  fireflies: "✨",
  leaves: "🍃",
  snowflakes: "❄️",
  raindrops: "💧",
  birds: "🐦",
  ladybugs: "🐞",
  flowers: "🌸",
  jellyfish: "🪼",
  rockets: "🚀",
  clouds: "☁️",
  "trace lines": "🖍️",
  "connect dots": "🔗",
  "drag & drop": "📦",
  "pinch & zoom": "🤏",
  "swipe patterns": "〰️",
  "follow the path": "🛤️",
  "catch the ball": "⚽",
  "pop & hold": "🫧",
  "slow drag": "🐢",
  "circle draw": "⭕",
  "zig-zag trace": "⚡",
  "target aim": "🎯",
  apples: "🍎",
  blocks: "🧱",
  fingers: "👆",
  coins: "🪙",
  cars: "🚗",
  ducks: "🦆",
  cookies: "🍪",
  hearts: "💗",
  frogs: "🐸",
  books: "📚",
  eggs: "🥚",
  fireworks: "🎆",
  whale: "🐳",
  crab: "🦀",
  octopus: "🐙",
  shark: "🦈",
  dolphin: "🐬",
  turtle: "🐢",
  starfish: "🐚",
  seahorse: "🐠",
  bee: "🐝",
  ant: "🐜",
  caterpillar: "🐛",
  snail: "🐌",
  spider: "🕷️",
  grasshopper: "🦗",
  storm: "⛈️",
  tornado: "🌪️",
  fog: "🌫️",
  lightning: "⚡",
  planet: "🪐",
  earth: "🌍",
  astronaut: "👨‍🚀",
  telescope: "🔭",
  comet: "☄️",
  soccer: "⚽",
  basketball: "🏀",
  football: "🏈",
  tennis: "🎾",
  volleyball: "🏐",
  pingpong: "🏓",
  golf: "⛳",
  archery: "🏹",
  backpack: "🎒",
  crayon: "🖍️",
  notebook: "📝",
  microscope: "🔬",
  schoolhouse: "🏫",
  couch: "🛋️",
  bed: "🛏️",
  shower: "🚿",
  stove: "🍳",
  window: "🪟",
  tulip: "🌷",
  pottedplant: "🪴",
  wateringcan: "🧑‍🌾",
  pets: "🐕",
  summer: "🏖️",
  watermelon: "🍉",
  icecream: "🍦",
  mittens: "🧤",
  teddy: "🧸",
  pillow: "🛏️",
  strawberry: "🍓",
  orange: "🍊",
  potato: "🥔",
  blueberry: "🫐",
  elephant: "🐘",
  giraffe: "🦒",
  mouse: "🐭",
  dinosaur: "🦖",
  fairy: "🧚",
  dragon: "🐉",
  castle: "🏰",
  crown: "👑",
  pig: "🐷",
  cow: "🐄",
  tractor: "🚜",
  hay: "🌾",
  boots: "👢",
  snowman: "⛄",
  tent: "🎪",
  juggler: "🤹",
  ticket: "🎟️",
  popcorn: "🍿",
  clown: "🤡",
  bathtub: "🛁",
  toothbrush: "🪥",
  sponge: "🧽",
  bucket: "🪣",
  toilet: "🚽",
  towel: "🧺",
  plate: "🍽️",
  salt: "🧂",
  coffee: "☕",
  teapot: "🫖",
  pot: "🍲",
  cup: "🥤",
  pineapple: "🍍",
  cherry: "🍒",
  broccoli: "🥦",
  tomato: "🍅",
  lettuce: "🥬",
  chili: "🌶️",
  garlic: "🧄",
  onion: "🧅",
  zebra: "🦓",
  monkey: "🐒",
  penguin: "🐧",
  owl: "🦉",
  duck: "🦆",
  parrot: "🦜",
  eagle: "🦅",
  swan: "🦢",
  chick: "🐤",
  hamster: "🐹",
  ladybug: "🐞",
  kite: "🪁",
  soap: "🧼",
  acorn: "🌰",
  trex: "🦖",
  egg: "🥚",
  footprint: "🦶",
  volcano: "🌋",
  fern: "🌿",
  bone: "🦴",
  meteor: "☄️",
  horse: "🐴",
  chicken: "🐔",
  sheep: "🐑",
  corn: "🌽",
  wand: "🪄",
  knight: "🛡️",
  sweater: "🧶",
  door: "🚪",
};

const LABEL_EMOJI: Record<string, string> = {
  dog: "🐶",
  cat: "🐱",
  rabbit: "🐰",
  frog: "🐸",
  fox: "🦊",
  bear: "🐻",
  koala: "🐨",
  lion: "🦁",
  apple: "🍎",
  banana: "🍌",
  pizza: "🍕",
  "ice cream": "🍦",
  cake: "🍰",
  donut: "🍩",
  carrot: "🥕",
  grapes: "🍇",
  car: "🚗",
  bus: "🚌",
  rocket: "🚀",
  plane: "✈️",
  train: "🚂",
  motorbike: "🏍️",
  bike: "🚲",
  boat: "⛵",
  happy: "😊",
  sad: "😢",
  surprised: "😲",
  angry: "😠",
  loved: "🥰",
  tired: "😴",
  excited: "🤩",
  laughing: "😂",
  calm: "😌",
  thinking: "🤔",
  flower: "🌸",
  sunflower: "🌻",
  tree: "🌳",
  leaf: "🍃",
  rainbow: "🌈",
  star: "⭐",
  moon: "🌙",
  sun: "☀️",
  shirt: "👕",
  pants: "👖",
  socks: "🧦",
  coat: "🧥",
  scarf: "🧣",
  dress: "👗",
  shoes: "👟",
  hat: "🎩",
  hammer: "🔨",
  brush: "🖌️",
  wrench: "🔧",
  ruler: "📏",
  spoon: "🥄",
  pencil: "✏️",
  scissors: "✂️",
  tape: "📎",
  guitar: "🎸",
  piano: "🎹",
  violin: "🎻",
  drum: "🥁",
  voice: "🎤",
  headphones: "🎧",
  note: "🎵",
  bell: "🔔",
  circle: "⭕",
  square: "🟦",
  triangle: "🔺",
  diamond: "🔶",
  oval: "🥚",
  rectangle: "🟧",
  heart: "❤️",
  one: "1️⃣",
  two: "2️⃣",
  three: "3️⃣",
  four: "4️⃣",
  five: "5️⃣",
  six: "6️⃣",
  seven: "7️⃣",
  eight: "8️⃣",
  red: "🔴",
  blue: "🔵",
  green: "🟢",
  yellow: "🟡",
  purple: "🟣",
  black: "⚫",
  white: "⚪",
  soft: "🧸",
  rough: "🪨",
  smooth: "🪞",
  bumpy: "🧱",
  sticky: "🍯",
  fuzzy: "🧶",
  hard: "💎",
  wet: "💧",
  spring: "🌸",
  autumn: "🍂",
  winter: "❄️",
  rain: "🌧️",
  snow: "⛄",
  wind: "🌬️",
  hand: "✋",
  foot: "🦶",
  eye: "👁️",
  ear: "👂",
  nose: "👃",
  mouth: "👄",
  knee: "🦵",
  arm: "💪",
  table: "🪑",
  ball: "⚽",
  book: "📖",
  puzzle: "🧩",
  clap: "👏",
  tap: "👆",
  hum: "🎶",
  ring: "🔔",
  step: "🦶",
  turn: "🔄",
  reach: "🙌",
  run: "🏃",
  jump: "🤸",
  roll: "🤾",
  walk: "🚶",
  berry: "🫐",
  wake: "🌅",
  wash: "🧼",
  eat: "🍽️",
  bathroom: "🚽",
  paste: "🦷",
  rinse: "💧",
  sit: "🪑",
  look: "👀",
  bite: "🍴",
  clean: "🧽",
  water: "🚰",
  dry: "🤲",
  pajamas: "🌙",
  teeth: "🦷",
  story: "📖",
  sleep: "😴",
  bag: "🎒",
  snack: "🍫",
  zip: "🤐",
  fork: "🍴",
  napkin: "🧻",
  list: "📝",
  cart: "🛒",
  choose: "🛍️",
  pay: "💳",
  start: "🎬",
  problem: "⚡",
  try: "🏃",
  end: "🏁",
  rest: "😌",
  "red car": "🚗",
  "blue dot": "🔵",
  rose: "🌹",
  "green dot": "🟢",
  "blue block": "🟦",
  lemon: "🍋",
  "yellow dot": "🟡",
  cookie: "🍪",
  brick: "🧱",
  tile: "🔲",
  box: "📦",
  song: "🎵",
  butterfly: "🦋",
  face: "🙂",
  scribble: "🖍️",
  cloud: "☁️",
  roof: "🏠",
  mountain: "⛰️",
  slice: "🍕",
  up: "⬆️",
  down: "⬇️",
  left: "⬅️",
  right: "➡️",
  center: "🎯",
  beginning: "🌅",
  help: "🤝",
  solve: "🏁",
  first: "1️⃣",
  next: "2️⃣",
  then: "3️⃣",
  after: "4️⃣",
  last: "5️⃣",
  na: "👄",
  ta: "👄",
  ba: "👄",
  ma: "👄",
  va: "👄",
};

const KEYWORD_EMOJI: [string, string][] = [
  ["cream", "🍦"],
  ["dot", "⚫"],
  ["block", "🧱"],
];

export function getThemeVisual(theme: string): string {
  return THEME_EMOJI[theme.trim().toLowerCase()] || "⭐";
}

export function emojiFor(label: string): string | undefined {
  const key = label.trim().toLowerCase().replace(/\s+/g, " ");
  const direct = LABEL_EMOJI[key];
  if (direct) return direct;
  for (const [needle, emoji] of KEYWORD_EMOJI) {
    if (key.includes(needle)) return emoji;
  }
  return undefined;
}

const FALLBACK_PALETTE = [
  "bg-rose-200 text-rose-700 border-rose-300",
  "bg-sky-200 text-sky-700 border-sky-300",
  "bg-amber-200 text-amber-700 border-amber-300",
  "bg-emerald-200 text-emerald-700 border-emerald-300",
  "bg-violet-200 text-violet-700 border-violet-300",
  "bg-orange-200 text-orange-700 border-orange-300",
];

export function letterMedalClass(label: string): string {
  let hash = 0;
  for (let index = 0; index < label.length; index += 1) {
    hash = (hash * 31 + label.charCodeAt(index)) >>> 0;
  }
  return FALLBACK_PALETTE[hash % FALLBACK_PALETTE.length];
}

export function LetterMedal({ label, className = "" }: { label: string; className?: string }) {
  const initial = label.trim().charAt(0).toUpperCase() || "?";
  return (
    <span
      aria-hidden="true"
      className={`grid place-items-center rounded-2xl border-2 font-black ${letterMedalClass(label)} ${className}`}
    >
      {initial}
    </span>
  );
}
